### ISSUE TITLE
new update 1.2.0 cant load mods

### ISSUE THREAD

**Issue by danicloudz** [SpectrumQT/WWMI#13]
it works on 1.1+ but now its not working

**Comment by highonbamboo** [comment]
https://gamebanana.com/tools/17752

1.2 Few Characters Affected
Only a few characters have been affected by this patch, with some changes being more notable than others.

Minor Changes (Hash Change)
Calcharo
Rover (Female and Male)
Baizhi
Yinlin
Jiyan

Major Changes (Remap):
Verina 

Complex Changes:
Changli

**Comment by SpectrumQT** [comment]
Stated issue has nothing to do with WWMI or WWMI Tools. WWMI 0.7.1 is fully compatible with WuWa 1.2. You should look for mod updates or mod auto-updaters, there're quite a few on GB. I recommend [this one](https://gamebanana.com/tools/17752).
