### ISSUE TITLE
im sorry but

### ISSUE THREAD

**Issue by crez-ol** [SpectrumQT/WWMI#14]
there's a Sucrose in my WWMI files is it broken?💀
![image](https://github.com/user-attachments/assets/3073e94a-f252-4249-9922-8c3688b3f4c8)

**Comment by leotorrez** [comment]
if you remove it, everything breaks. Must keep the crose safe

**Comment by SpectrumQT** [comment]
It's crucial legacy dependency. Dare not to ever touch it! :P
