### ISSUE TITLE
skins texture not loading properly

### ISSUE THREAD

**Issue by eaternalz** [SpectrumQT/WWMI#15]
whenever i open wuva with mods they skins texture is always wrong and sometimes the whole skin just doesn't load after like 5 minutes it dose eventually load but if i switch characters same issue the other characters are now not loaded .if i try loading them all wait 5 min for each the other characters just go back to being glitched when the other loads.i have a gtx 1660ti and a amd ryzen 5 5500 with 16 GB
ram. is it a computer issue or an issue with wwmi?

![image](https://github.com/user-attachments/assets/c8e6b17e-9d7d-4fea-ac45-f119db676d23)

![image](https://github.com/user-attachments/assets/261565e7-bc10-4435-af42-dda91e6fba54)

**Comment by SpectrumQT** [comment]
Does it happen with original d3dx.ini? You didn't modify it or replace with 'recommended' coming from some mod? Please give me its full listing.

**Comment by eaternalz** [comment]
> Does it happen with original d3dx.ini? You didn't modify it or replace with 'recommended' coming from some mod? Please give me its full listing.

no all i did was download the mods files and put them in the mods folder i didnt edit anything for the mods

**Comment by SpectrumQT** [comment]
Please provide links to any mods with issues. I also need to know your windows version and PC specs and frame dump of any unmodded character with issues. To make frame dump, set in-game resolution to minimum and follow **Frame Dump Objects Extraction** from [this guide](https://github.com/SpectrumQT/WWMI-TOOLS/blob/main/guides/modder_guide.md#frame-dump-objects-export). Then remove all *dds file from it, zip and post to any cloud like Google Drive (don't forget to open link to public).

**Comment by eaternalz** [comment]
> Please provide links to any mods with issues. I also need to know your windows version and PC specs and frame dump of any unmodded character with issues. To make frame dump, set in-game resolution to minimum and follow **Frame Dump Objects Export** from [this guide](https://github.com/SpectrumQT/WWMI-TOOLS/blob/main/guides/modder_guide.md#frame-dump-objects-export). Then remove all `.dds` files from resulting folder to reduce its size, zip it and upload to any cloud storage like Google Drive (don't forget to open link to public).

sorry if i didn't make this clear before but the texture issue is only with modded characters  and the non modded characters have no issue and, as i have mentioned before i have a GTX 1660ti and an AMD Ryzen 5 5500 with 16 GB ram i am using windows 10 pro and the mods i am using are:

-https://gamebanana.com/mods/536995

-https://gamebanana.com/mods/534747

-https://gamebanana.com/mods/525884

tell me if you still need the frame dump of the unmodded characters or any other information and thanks for helping

**Comment by SpectrumQT** [comment]
Well, all listed mods are valid WWMI mods indeed. From your specs I can suggest that game may use some low-end assets that don't have their hashes in mods. For now, I'd suggest to install [XXMI Launcher](https://github.com/SpectrumQT/XXMI-Launcher) and tell me how it goes, it'll do the game configuration for you automatically. Probably you're missing some installation steps.

**Comment by eaternalz** [comment]
worked! thanks alot still a bit glitchy and slows my game down but atleast the mods work now

**Comment by SpectrumQT** [comment]
You're welcome. If you're experiencing FPS drops, you can also try to use 'Apply Performance Tweaks' experimental option in Launcher Settings. If they'll make things worse, just remove them from the file. Refer to option tooltip for more info. You can also try to increase Process Priority to High in the same tab.
