### ISSUE TITLE
Can't open the game

### ISSUE THREAD

**Issue by BrandosGro** [SpectrumQT/WWMI#16]
After I open WWMI Loader, the game just doesn't open. No pop-up or anything. I did everything right.

**Comment by SpectrumQT** [comment]
Well, if you're sure that you did everything right, my only suggestion would be to try [XXMI Launcher](https://github.com/SpectrumQT/XXMI-Launcher), and to provide its log file if it'll also fail to start the game.

**Comment by BrandosGro** [comment]
> Well, if you're sure that you did everything right, my only suggestion would be to try [XXMI Launcher](https://github.com/SpectrumQT/XXMI-Launcher), and to provide its log file if it'll also fail to start the game.

I tried, somehow it just shows the game without the icon on the taskbar and then disappeared
