### ISSUE TITLE
About DX12

### ISSUE THREAD

**Issue by percy4** [SpectrumQT/WWMI#17]
The GAME update has updated DX12, which seems to be more friendly to 40-series GPUs. So can we support DX12 in WWMI?
And my mod causes a lot of red error messages in the top left corner, is there a way to hide the red error messages?

**Comment by SpectrumQT** [comment]
WWMI is unlikely to ever support DX12 unless 3dmigoto will be rebuilt for this purpose by its developers. Such accomplishment is far beyond the WWMI project scope.

As for errors, I'd suggest to move to XXMI Launcher. New XXMI binaries got proper error supression method, and it's enabled by default. See updated installation instruction.
