### ISSUE TITLE
[Error] 'gbk' codec can't decode byte 0xba in position 3766: illegal multibyte sequence

### ISSUE THREAD

**Issue by JWYdog** [SpectrumQT/WWMI#18]
Here's the log

2024-09-22 10:36:41,552,552 root ERROR Traceback (most recent call last):
  File "app.py", line 361, in launch
  File "core\event_manager.py", line 43, in Fire
  File "core\packages\model_importers\model_importer.py", line 232, in start_game
  File "core\packages\model_importers\wwmi_package.py", line 163, in initialize_game_launch
  File "core\packages\model_importers\wwmi_package.py", line 176, in update_engine_ini
  File "core\utils\ini_handler.py", line 82, in __init__
  File "core\utils\ini_handler.py", line 93, in from_file
UnicodeDecodeError: 'gbk' codec can't decode byte 0xba in position 3766: illegal multibyte sequence

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 407, in wrap_errors
  File "app.py", line 371, in launch
Exception: WWMI Loading Failed:
'gbk' codec can't decode byte 0xba in position 3766: illegal multibyte sequence

**Comment by SpectrumQT** [comment]
Now that's weird, I was expecting this file to be ASCII-only. Please upload **Engine.ini** file (example location: `C:/Games/WutheringWavesj3oFh/Wuthering Waves Game/Client/Saved/Config/WindowsNoEditor/Engine.ini`) to any cloud storage, open public access for it, and share the link. And yes, I need the file itself, not a copy of its contents from some text editor.

**Comment by JWYdog** [comment]
> Now that's weird, I was expecting this file to be ASCII-only. Please upload **Engine.ini** file (example location: `C:/Games/WutheringWavesj3oFh/Wuthering Waves Game/Client/Saved/Config/WindowsNoEditor/Engine.ini`) to any cloud storage, open public access for it, and share the link. And yes, I need the file itself, not a copy of its contents from some text editor.

Link:
https://drive.google.com/file/d/1Vd2sPuycZ_TQKcWaLVdFUsmaz_C9gT-H/view?usp=drive_link

This Engine.ini works fine in version 0.7.1，Could the problem be caused by comments in the file?

**Comment by JWYdog** [comment]
When I tried to delete the configured comments, the tool worked correctly.

**Comment by SpectrumQT** [comment]
Well, before launcher release handling Engine.ini was entirely up to user, but now everything is automated and program expects valid ini syntax. With 0.9.1 launcher update I'll make it tolerate non-ASCII characters, but if there'll ever be a need to change some value, comment of this value will be erased.

**Comment by SpectrumQT** [comment]
Actually, nevermind, I'll make it support inline comments for this file.

**Comment by SpectrumQT** [comment]
Launcher 0.9.1 update live, it should resolve the issue. Feel free to add comments back and tell me how it goes.
