### ISSUE TITLE
Is there a particular reason behind this being moved to XXMI?

### ISSUE THREAD

**Issue by feedbackstuff** [SpectrumQT/WWMI#22]
I'm sure some appreciate the push being made to have mods more organized and compatible, but to have that the only option moving forward is a bit... forced

Having a portable standalone version of this tool like before would be ideal for some, I don't play any of the other games listed, it feels a bit bloated to have it all installed with everything stitched together.

I'm hoping you can reconsider, for convenience sake.

Regards,
feedbackstuff

**Comment by spiwar** [comment]
+1

**Comment by SpectrumQT** [comment]
WWMI benefits from the launcher the most, as it allows even completely illiterate people (aka the most part of the userbase) to correctly install and run WWMI without plaguing me with complaints. Aside from that, launcher also enables more reliable 3dm dll hooking, does extra WWMI configuration and simplifies release / update process both for users & individual developers.

I will **not** go back to the old release format, as it's technically inferior and I don't have time to support both. And, common, anyone in 2024 can afford to spend 5MB on the mentioned "bloat" (few images and code modules that won't even be loaded until accociated game is selected).

Also, if you don't want to see the launcher window, you can use the quick launch shortcut.
