### ISSUE TITLE
[1.4 Bug] All Rover Skins Glitch Partially on 1.4 Official Update

### ISSUE THREAD

**Issue by weberlu88** [SpectrumQT/WWMI#23]
After the official 1.4 update, it seems like all Rover Skins are not loaded correctly. Hope someone provide a general fix on Rover Skins.

For example on these 2 mods:
- Goddess over Rover https://gamebanana.com/mods/531239
- Rover F Stylish Beach Jog Outfit https://gamebanana.com/mods/548746

The mods currently look like:
![Rover01](https://github.com/user-attachments/assets/20f74904-794c-408e-8e03-d6ca36a1dcaa)
![Rover02](https://github.com/user-attachments/assets/1d4e46ef-7f57-4393-b639-81b31f2f9b25)

**Comment by highonbamboo** [comment]
Mods need to be updated. It's not a WWMI problem.
https://gamebanana.com/tools/18446
