### ISSUE TITLE
When will dx12 be supported?

### ISSUE THREAD

**Issue by AsukaSoryu0** [SpectrumQT/WWMI#24]
Great author, recently turned on auto hdr for windows in the game, with good results. But auto hdr will have problems with dx11 in the game, dx12 will not have problems. So I choose between hdr and mod. Does wwmi have any plans to use dx12 in the future? Thanks again wwmi

**Comment by SpectrumQT** [comment]
WWMI is unlikely to ever support DX12 unless 3dmigoto will be rebuilt for this purpose by its developers. Such accomplishment is far beyond the WWMI project scope.
