### ISSUE TITLE
How to make UI related mods

### ISSUE THREAD

**Issue by yixyming** [SpectrumQT/WWMI#25]
I'm a gamer and I want to hide some UI, but with the update some code failing, I want to know where I can read and learn articles about the code

**Comment by yixyming** [comment]
I would be very grateful

**Comment by SpectrumQT** [comment]
Hello! It's quite complicated subject that requires you to know how D3D works (aka how API calls are structured and executed). Your question is too general to be answered, and different UI elements require drastically different approach (and no, I will not be answering questions about related specifics). If you're really interested, I'd suggest to do some heavy lifting:

1. [Silent's Guides](https://github.com/SilentNightSound/GI-Model-Importer/tree/main/Guides)
2. [3dmigoto wiki](https://github.com/bo3b/3Dmigoto/wiki)
3. DirectX documentation and articles on web

**Comment by yixyming** [comment]
I'm sorry I can't articulate my problem because I'm a layman in this area, I just understood and learned by studying the ini files of the mod author's work and used it on my own ini files, but I will continue to learn, thank you for your help, I believe these resources will allow me to learn a lot  ^_^
