### ISSUE TITLE
Ban for Changing Console Variables in Engine.ini?

### ISSUE THREAD

**Issue by subzfx** [SpectrumQT/WWMI#4]
Will I not get banned for Changing the Game File? We are adding "Console Variables" lines inside "Engine.ini" isn't that technically changing the game files?

**Comment by SpectrumQT** [comment]
Technically, when you're changing settings in game, you're changing game files. Changing configs or removing incompatible plugins never was bannable offense. I'd rather expect ban for fake dx11 dll injection that is 3dmigoto.

**Comment by subzfx** [comment]
> Technically, when you're changing settings in game, you're changing game files. Changing configs or removing incompatible plugins never was bannable offense. I'd rather expect ban for fake dx11 dll injection that is 3dmigoto.

Wait WWMI is injecting dll into the game itself? is it not like it's only changing what the GPU data shows?
