### ISSUE TITLE
0xc000007b

### ISSUE THREAD

**Issue by HuanKongzzz** [SpectrumQT/WWMI#5]
Run WWMI.exe prompt missing msvcr120.dll after using the search engine search after the installation of the above file and error 0xc000007b I am 64-bit win11 but whether it is 32-bit or 64-bit installation is 0xc000007b error

**Comment by SpectrumQT** [comment]
Hello!

Please try [Visual C++ Redistributable Packages for Visual Studio 2013](https://www.microsoft.com/en-us/download/details.aspx?id=40784).

I'll rebuild 3dm binaries myself for 0.7.0 so they'll require more modern versions.

**Comment by HuanKongzzz** [comment]
> Hello!
> 
> Please try [Visual C++ Redistributable Packages for Visual Studio 2013](https://www.microsoft.com/en-us/download/details.aspx?id=40784).
> 
> I'll rebuild 3dm binaries myself for 0.7.0 so they'll require more modern versions.

The problem with 0xc000007b still exists
![3d722ea7-32cb-4cac-a399-779d0b4bab6f(1)](https://github.com/SpectrumQT/WWMI/assets/119497994/c9d0adc7-0383-4cb9-a491-f4fdf2318cc8)

**Comment by SpectrumQT** [comment]
Hello! Please try out [the latest WWMI release](https://github.com/SpectrumQT/WWMI/releases/latest) (make sure to install [the latest MSVC++](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)). It should fix your issue.

**Comment by HuanKongzzz** [comment]
Thanks! The issue was resolved after I updated to version 0.7.0
