### ISSUE TITLE
Errors in drawing VS's with encore?

### ISSUE THREAD

**Issue by Apoc1011** [SpectrumQT/WWMI#6]
Hello spectrum, sorry to bother you again with another problem. But I seem to have found a new bug. Not sure if your aware of it, so I will post my findings down below.

WWMI version : 0.6.2
\

Character Tested : Encore
\

Issue : Component 4 ( Front hair piece ), doesn't get properly drawn when other components are missing pieces of there mesh.
\

Abstract :  Upon extensive testing with exporting various altercations of the mod. I have found that extensive changes in a mesh of a model , results in the component for her front piece of hair missing. This only seems to occur when the mesh itself is altered VIA subtraction, and not when the component is removed, or other meshes added.
\

---------------------------------------------------------------------------------
- When exporting the default model, no changes are noticeable.
 
![documentation 2](https://github.com/SpectrumQT/WWMI/assets/174495042/a0aed830-b296-4411-8e32-5f6449346070)

- Even with slight edits to the mesh via subtraction, no abnormal changes can be noticed.

![docu3](https://github.com/SpectrumQT/WWMI/assets/174495042/121c92a4-9b7b-4ee3-887a-ec7020385491)
![docu4](https://github.com/SpectrumQT/WWMI/assets/174495042/a172382f-f9b7-477b-8133-47d114694cc6)

- however, when alterting a large area, such as deleting all faces. The hair becomes greyed out and diluted

![docu5](https://github.com/SpectrumQT/WWMI/assets/174495042/0aa4ecf8-6b76-438a-902e-8a5d7d4f618a)
![documentation 1](https://github.com/SpectrumQT/WWMI/assets/174495042/ac77d982-dbda-4ec0-9760-984153bfe7ed)
![docu6](https://github.com/SpectrumQT/WWMI/assets/174495042/b8a04cd7-af85-4f8c-969e-859416bf9813)

- I believed, that there was something wrong with Component 0, so instead I tried altercations to other meshes. 

- So I removed some elements from Component3

![docu7](https://github.com/SpectrumQT/WWMI/assets/174495042/3e37dde7-54de-497d-9315-26e00f827c7d)

- The reason I left, part of the mesh intact, was to highlight that it occurs only when large areas of the mesh is removed, rather than the entire thing

![docu8](https://github.com/SpectrumQT/WWMI/assets/174495042/8a5b1b9d-d59e-42b1-b566-822da6386fa6)

- I tried to figure out if this was an issue with the mesh itself, or with the entire component.
- So I removed the entirety of component 0 to see what the results were

![docu9](https://github.com/SpectrumQT/WWMI/assets/174495042/0fe7f934-5c86-4887-b43f-65d41cdb4768)
 
![docu10](https://github.com/SpectrumQT/WWMI/assets/174495042/84b3821f-29fb-49f1-90da-a20d4d242b81)

- seeing as the problem occurred in only component 4, my soloution was to delete, it and merge it with component 5 instead.

![docu12](https://github.com/SpectrumQT/WWMI/assets/174495042/215d561e-7837-4ea5-9f2a-f43ac6f2db8c)
![docu11](https://github.com/SpectrumQT/WWMI/assets/174495042/eb67deed-a1e6-49c7-a1b6-ff18459d27d9)

- this works as a temporary fix, but some details are still lost, such as the eyebrows now being behind the hair. 

- I also tried adding a mesh, instead of subtracting it, but the results were the same. 

- Only when parts of the original mesh is being removed, does this hair glitch occur. 

- So I figured it would be best to document everything and send it over to you.

-------------------------------------------
\

Thoughts : 
I am not sure where the issue lies, but it often feels like the system is trying to draw onto a mesh that no longer exists. So it draws onto the nearest thing it can find, which might be the hair component 4, since it feels like that is rendered above everything.
And since the mesh no longer exists, it creates these gaps in the texture, where its blank or invisible. 
I am no coding experct, so I probably sound like an idiot right now.

But either way, once again, I hope this info proves to be useful.

**Comment by Apoc1011** [comment]
Addenum:  I am not sure why, but after restarting both blender and the game, and loading backup the same mods, most of the issues have been fixed except this small piece right here. 
![wholesome](https://github.com/SpectrumQT/WWMI/assets/174495042/ae963bb8-d01b-4f49-a82f-84e0c31dd17e)

Would this happen to be something on my end? As I was trying to inject the mods directly and reload them to test. Would it be cause I didnt allow everything to properly restart/reset ?

**Comment by SpectrumQT** [comment]
Hello! I'm sorry that it wasn't added to known ussues. Flickering and ghosting is caused by vs-cb usage of 0.6.X mod.ini format. Also it often fixes itself after the game restart. I've managed to switch to vb0 usage for upcoming 0.7.0, re-exporting your mod.ini's with updated WWMI Tools (after its release) should get rid of those issues.

**Comment by Apoc1011** [comment]
oh ok. Glad to know I wasnt going crazy. Sorry for reposting known issues. Thanks again for all the hard work

**Comment by SpectrumQT** [comment]
Please try out the latest [WWMI](https://github.com/SpectrumQT/WWMI/releases/latest) and [WWMI Tools](https://github.com/SpectrumQT/WWMI-TOOLS/releases/latest) releases. Mod should get fixed after re-export.

**Comment by Apoc1011** [comment]
Things are working great now. As always , thank you for the hard work. I appreciate your work ethic. 
Would it be ok for me to continue posting any future bugs I find?

**Comment by SpectrumQT** [comment]
Sure thing, that's exactly what Issues section is made for. It's always useful to have more context when fighting bugs.
