### ISSUE TITLE
Game Either Crashes or Will not Start when 3D Migoto is ready to latch onto Game

### ISSUE THREAD

**Issue by raphyand** [SpectrumQT/WWMI#7]
Hi, 

I was trying to begin modding WuWa when it looks like I've come up with an issue I don't see anyone else has encountered (unless someone has) for version 0.7. 

It'll last from 3 seconds to 11 seconds, where I can see the process start on my Task Manager, but it won't progress to opening full screen.  Based on turning on Logging, it looks like there might be a deadlock issue -- here's the WWMI and Logging folder, shared in a link: https://drive.google.com/drive/folders/1LdsNgrzfdxiEzyARpVGqO8xMZ-phGEqC?usp=drive_link . 

I'll also paste an image of what I caught:
![Screenshot 2024-07-22 223909](https://github.com/user-attachments/assets/770a9844-55ae-431a-8221-e1d3587f41b2) . 

Am happy to help provide more for this, thanks.

**Comment by SpectrumQT** [comment]
Hello! Linked logs aren't public I'm afraid.

**Comment by raphyand** [comment]
Ah, sorry.  Here try this: https://drive.google.com/drive/folders/1LdsNgrzfdxiEzyARpVGqO8xMZ-phGEqC?usp=sharing .

**Comment by SpectrumQT** [comment]
Unfortunately, nothing in provided logs is pointing at the cause. Probably there's something wrong with `xaudio2_9.dll`, but I can't say for sure. Considering the sheer rarity of reported issue (1/20000+), it's very specific to your OS installation and may be caused by data corruption. I'd suggest to run system integrity check or reinstall OS if you're that dedicated.

**Comment by raphyand** [comment]
Hello again, I was able to do a workaround with this by having the log statements: 

```
; Log all API usage
calls = 1

; Super verbose massive log
debug = 0

; Unbuffered logging to avoid missing anything at file end
unbuffered = 1
```

However, with the new Installer, it looks like it overwrites the d3dx file when I launch the game, and causes 
```
; Super verbose massive log
debug = 1
```

which causes my game to become super laggy.  

Is there a way to prevent overwriting with the Installer? Or to just keep `verbose` as 0?
